### ISSUE TITLE
RFC 3986 Support

### ISSUE THREAD

**Issue by simplyatul** [golgote/neturl#19]
Does neturl comply with RFC 3986?

**Comment by zhangcunli** [comment]
neturl can't parse url like: //www.example.com 
RFC 3986
@golgote

**Comment by golgote** [comment]
Parsing `//www.example.com` works for me, as shown in the tests.    
Neturl complies with RFC 2396. RFC 3986 is a more recent version of the same thing. I don't know what the differences are between these two RFC.
